Import('*')

Source('TMStorage.cpp', lib='TM')
Source('TMCoherence.cpp', lib='TM')
Source('TMContext.cpp', lib='TM')
Source('TMState.cpp', lib='TM')
Source('HWGate.cpp', lib='TM')
Source('PrivateCache.cpp', lib='TM')
