#ifndef LIMETYPE_H
#define LIMETYPE_H

enum LIMEINST {
	LIME_NORM 		= 0x0000,
	LIME_CALL		= 0x0001,
	LIME_RET		= 0x0010,
	LIME_BAR  		= 0x0100,
	LIME_BAR_CALL 	= LIME_BAR+LIME_CALL,
	LIME_BAR_RET  	= LIME_BAR+LIME_RET,
	LIME_JOIN 		= 0x0200,
	LIME_JOIN_CALL 	= LIME_JOIN+LIME_CALL,
	LIME_JOIN_RET 	= LIME_JOIN+LIME_RET,
	LIME_BR	  		= 0x1000,
	LIME_MEM  		= 0x2000,
};

#include "LimeMark.h"

#endif
