#ifndef LIMEMARK_H
#define LIMEMARK_H

enum LIMEMARK {
	LM_PER_INS_TIME 	= 0x1234,
	LM_PER_INS_DATA 	= 0x4321,
	LM_PER_INS_MEM_DATA = 0xCDEF,
	LM_PER_THREAD_TIME 	= 0xAAAA,
	LM_PROG_NAME 		= 0xFFFF,
};

#endif
